// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCysoe1Q7XvtYIcx5u4bwbLhFbtuaY3VEI',
    appId: '1:806620359391:web:d51cdd531dc212a3a2976a',
    messagingSenderId: '806620359391',
    projectId: 'beartahan-2e52d',
    authDomain: 'beartahan-2e52d.firebaseapp.com',
    storageBucket: 'beartahan-2e52d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoitcJEwoIZC_3ExUGddDQg2iX60ZdZ8A',
    appId: '1:806620359391:android:ff6d3f156b2361a0a2976a',
    messagingSenderId: '806620359391',
    projectId: 'beartahan-2e52d',
    storageBucket: 'beartahan-2e52d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqOIYqWhg7QLCm2U9JYlNT_553wmnAXwY',
    appId: '1:806620359391:ios:440df7ff48b376cea2976a',
    messagingSenderId: '806620359391',
    projectId: 'beartahan-2e52d',
    storageBucket: 'beartahan-2e52d.firebasestorage.app',
    iosClientId: '806620359391-r5kf6pqv1f0qt5n9cv026jr6vtl82dpm.apps.googleusercontent.com',
    iosBundleId: 'com.applets5.bearTahan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqOIYqWhg7QLCm2U9JYlNT_553wmnAXwY',
    appId: '1:806620359391:ios:440df7ff48b376cea2976a',
    messagingSenderId: '806620359391',
    projectId: 'beartahan-2e52d',
    storageBucket: 'beartahan-2e52d.firebasestorage.app',
    iosClientId: '806620359391-r5kf6pqv1f0qt5n9cv026jr6vtl82dpm.apps.googleusercontent.com',
    iosBundleId: 'com.applets5.bearTahan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCysoe1Q7XvtYIcx5u4bwbLhFbtuaY3VEI',
    appId: '1:806620359391:web:cd8c582e5bbaaf82a2976a',
    messagingSenderId: '806620359391',
    projectId: 'beartahan-2e52d',
    authDomain: 'beartahan-2e52d.firebaseapp.com',
    storageBucket: 'beartahan-2e52d.firebasestorage.app',
  );
}
